echo "Loading ~/bash/.bash_aliases";
alias ll='ls -alF --color=auto'
alias la='ls -A --color=auto'
alias l='ls -CF --color=auto'
alias ls='ls -Ga --color=auto'
alias lsa='ls -Gal --color=auto'
alias dir='ls'
alias onedrivesync='onedrive --synchronize'
alias onedrve-update='onedrive --resync'
alias cls='clear'
alias rar='run-as-root'
alias restart-web='restart-all-websites'
alias opencode='code .'
alias opensucode='open-current-folder-as-sudo-in-code'
alias openassu='open-current-folder-as-sudo'
alias reload='source ~/.profile'
alias rn='restart-nginx'
alias Rn='rn'
alias rs='systemctl status nginx.service'
alias Rs='rs'